apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
  namespace: binpak
  labels:
    app: debug
spec:
  replicas: 1
  template:
    metadata:
      name: debug
      labels:
        app: debug
    spec:
      containers:
        - name: debug
          image: ubuntu:latest
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args: [ "-c", "while true; do echo hello; sleep 10;done" ]
      restartPolicy: Always
      serviceAccountName: metrics-reader
  selector:
    matchLabels:
      app: debug
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-metrics
rules:
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
      - /metrics/*
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-metrics
subjects:
  - kind: ServiceAccount
    name: metrics-reader
    namespace: binpak
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-reader
  namespace: binpak
automountServiceAccountToken: true