---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: binpak-backend
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes", "services", "pods", "deployments", "endpoints" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "metrics.k8s.io" ]
    resources: [ "nodes", "services", "pods", "deployments", "endpoints" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binpak-backend
roleRef:
  kind: ClusterRole
  name: binpak-backend
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: binpak-backend
    namespace: binpak
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: binpak-backend
  namespace: binpak
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: binpak-ui
  namespace: binpak
automountServiceAccountToken: true
